exec1:
	go run ./exc1/main.go
exec2:
	go run ./exc2/main.go
exec3:
	go run ./exc3/main.go
exec4:
	go run ./exc4/main.go
exec5:
	go run ./exc5/main.go
all:
	go run ./exc1/main.go
	go run ./exc2/main.go
	go run ./exc3/main.go
	go run ./exc4/main.go
	go run ./exc5/main.go
